### ISSUE TITLE
Qt5’s native backend opens a ton of transparent windows

### ISSUE THREAD

**Issue by linkmauve** [Cloudef/loliwm#78]
`QT_QPA_PLATFORM=wayland-egl citra-qt` for example, will open 20 windows, one of which (the 16th) is the actual Qt window, all of the other ones being transparent.

**Comment by Cloudef** [comment]
Heh, most likely hidden X11 windows that should not be mapped.

**Comment by linkmauve** [comment]
This is native Wayland though, there shouldn’t be any X11 involved.

**Comment by Cloudef** [comment]
Oh.. I'll investigate, when I get home.

**Comment by Cloudef** [comment]
Seems like Qt does some very strange things. I have no idea why it creates 20 surfaces, and they all have shell_surface role. It does the same thing under weston, but you just don't see them there since they are invisible.

Neverthless wl_shell is really bad interface for desktop applications anyways. Should use xdg-shell, you can't close individual windows for example from compositor. (It's all controlled by application using the old interface)

**Comment by Cloudef** [comment]
This seems to be issue with current wayland implementation on Qt, every QWindow is actually shell-surface (even subwindows).
